name: ci-cd-emscripten

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repo
        uses: actions/checkout@v3
      - uses: mymindstorm/setup-emsdk@v14
      - name: Build html bundle
        run: em++ main.cpp engine/Engine.cpp engine/cell/Cell.cpp -s USE_SDL=2 -o index.html
      - uses: actions/upload-artifact@v4
        with:
          name: page
          path: |
            index.html
            index.wasm
            index.js
          if-no-files-found: error
  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: page
          path: .
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
